baseURL = "https://gocv.io/"
languageCode = "en-us"
title = "GoCV - Golang Computer Vision Using OpenCV 4"
theme = "learn"

[params]
  # Disable search function. It will hide search bar
  disableSearch = true
  editURL = "https://github.com/hybridgroup/gocv-site/edit/master/content/"

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
url = "https://github.com/hybridgroup/gocv"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-book'></i> Docs"
url = "https://pkg.go.dev/gocv.io/x/gocv"
weight = 20

[[menu.shortcuts]] 
name = "<i class='fa fa-twitter'></i> Twitter"
url = "https://twitter.com/GoCVio"
weight = 30
