baseURL = "https://gocv.io/"
languageCode = "en-us"
title = "GoCV - Golang Computer Vision Using OpenCV 4"
theme = "hugo-theme-relearn"

[params]
  # Disable search function. It will hide search bar
  disableSearch = true
  editURL = "https://github.com/hybridgroup/gocv-site/edit/release/content/"
  themeVariant = 'learn'

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
url = "https://github.com/hybridgroup/gocv"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-book'></i> Docs"
url = "https://pkg.go.dev/gocv.io/x/gocv"
weight = 20

[[menu.shortcuts]] 
name = "<i class='fab fa-mastodon'></i> Mastodon"
url = "https://mastodon.social/@gocv"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-bluesky'></i> BSky"
url = "https://bsky.app/profile/gocv.io"
weight = 40
